### ISSUE TITLE
About segmentation extractions

### ISSUE THREAD

**Issue by Aqrzz** [XuriGe1995/3SHNet#1]
Thank you for your excellent work. Can you show me the code for generating segmentation semantic features (%s_segmentations.npy, dims=(N,133,7,7)), segmentation maps (%s_seg_maps.npy, dims=(N, 64, 64), downsampleing to reduce the calculations) and category-one-hot(%s_cat_onehots.npy, dims=(N,133), or rather, which intermediate feature was taken from upsnet

**Comment by XuriGe1995** [comment]
Hi 
Thanks for your Attention.

About the segmentation features, they are computed with the code provided by [UPSNet](https://github.com/uber-research/UPSNet). You can directly employ the pre-trained UPSNet to extract the segmentation results and representations.
